config/routes.rb
Rails.application.routes.draw do
  get 'machinetype/index'
  root 'home#about'
  get 'home/about'
  get 'home/index'
  post 'home/index' => 'home#index'
  #get 'welcome/home'
  resources :aboutmes
  resources :grokkings
  resources :qanas
  resources :cpurcores
  resources :slacal

  get 'getcpu' => 'cpucores#home'
  get 'slacal/home_' => 'slacal#home '
  get 'home/about'
  get 'interview/index'
  post "machinetype/index" => 'machinetype#index'
  #post "home/aboutmes" => 'aboutmes#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aboutme.rb
class Aboutme < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grokking.rb
class Grokking < ApplicationRecord
end

app/models/qana.rb
class Qana < ApplicationRecord
end

app/controllers/cpucores_controller.rb
class CpucoresController < ApplicationController
	def home
		require 'net/http'
		
		@symbol = params[:sym]
		@url  =  'https://docs.microsoft.com/en-us/azure/virtual-machines/acu'
	end
end

app/controllers/grokkings_controller.rb
class GrokkingsController < ApplicationController
  before_action :set_grokking, only: [:show, :edit, :update, :destroy]

  # GET /grokkings
  # GET /grokkings.json
  def index
    @grokkings = Grokking.all
  end

  # GET /grokkings/1
  # GET /grokkings/1.json
  def show
  end

  # GET /grokkings/new
  def new
    @grokking = Grokking.new
  end

  # GET /grokkings/1/edit
  def edit
  end

  # POST /grokkings
  # POST /grokkings.json
  def create
    @grokking = Grokking.new(grokking_params)

    respond_to do |format|
      if @grokking.save
        format.html { redirect_to @grokking, notice: 'Grokking was successfully created.' }
        format.json { render :show, status: :created, location: @grokking }
      else
        format.html { render :new }
        format.json { render json: @grokking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grokkings/1
  # PATCH/PUT /grokkings/1.json
  def update
    respond_to do |format|
      if @grokking.update(grokking_params)
        format.html { redirect_to @grokking, notice: 'Grokking was successfully updated.' }
        format.json { render :show, status: :ok, location: @grokking }
      else
        format.html { render :edit }
        format.json { render json: @grokking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grokkings/1
  # DELETE /grokkings/1.json
  def destroy
    @grokking.destroy
    respond_to do |format|
      format.html { redirect_to grokkings_url, notice: 'Grokking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grokking
      @grokking = Grokking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grokking_params
      params.require(:grokking).permit(:topic, :article, :creationdate)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index, :team , :about]

  def common
  	@name ="Krishna Venkat"
  	@team_selected = 0
  end 

  def team

  end 

  def index
  	  	@team_selected = params[:team_number]
  end

 def about 
 end

end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController
  def index
  end
end

app/controllers/qanas_controller.rb
class QanasController < ApplicationController
  before_action :set_qana, only: [:show, :edit, :update, :destroy]

  # GET /qanas
  # GET /qanas.json
  def index
    @qanas = Qana.all
  end

  # GET /qanas/1
  # GET /qanas/1.json
  def show
  end

  # GET /qanas/new
  def new
    @qana = Qana.new
  end

  # GET /qanas/1/edit
  def edit
  end

  # POST /qanas
  # POST /qanas.json
  def create
    @qana = Qana.new(qana_params)

    respond_to do |format|
      if @qana.save
        format.html { redirect_to @qana, notice: 'Qana was successfully created.' }
        format.json { render :show, status: :created, location: @qana }
      else
        format.html { render :new }
        format.json { render json: @qana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qanas/1
  # PATCH/PUT /qanas/1.json
  def update
    respond_to do |format|
      if @qana.update(qana_params)
        format.html { redirect_to @qana, notice: 'Qana was successfully updated.' }
        format.json { render :show, status: :ok, location: @qana }
      else
        format.html { render :edit }
        format.json { render json: @qana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qanas/1
  # DELETE /qanas/1.json
  def destroy
    @qana.destroy
    respond_to do |format|
      format.html { redirect_to qanas_url, notice: 'Qana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qana
      @qana = Qana.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qana_params
      params.require(:qana).permit(:topic, :question, :answer, :createddate, :version)
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
end

app/controllers/slacal_controller.rb
class SlacalController < ApplicationController
 	def index
		@sla  = 10
	end

	def create
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cpucores_helper.rb
module CpucoresHelper
end

app/helpers/grokkings_helper.rb
module GrokkingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/machinetype_helper.rb
module MachinetypeHelper
end

app/helpers/qanas_helper.rb
module QanasHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/slacal_helper.rb
module SlacalHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cpucores/home.html.erb
<div class="main">
	<div class="container">
		<h1> Welcome to CPU Core Counter</h1>
	 	<%= @symbol %> </br>
	 

		<p1> Use the calculator to calculate sequnetial and composite SLA</p1> </br> </br>
	 	
	 	<!-- Example split danger button -->
				<div class="btn-group">
				  <button type="button" class="btn btn-danger">Action</button>
				  <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    <span class="sr-only">Toggle Dropdown</span>
				  </button>
				  <div class="dropdown-menu">
				    <a class="dropdown-item" href="#">Action</a>
				    <a class="dropdown-item" href="#">Another action</a>
				    <a class="dropdown-item" href="#">Something else here</a>
				    <div class="dropdown-divider"></div>
				    <a class="dropdown-item" href="#">Separated link</a>
				  </div>
				</div>
	</div>
</div>

app/views/home/_create_team.html.erb
<h1>Create Team page </h1>
<p>Hello Create page clicked from index page </p>

<br/>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <meta name="viewport" content="width-device-width", intital-scale=1">
 

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      

      <li class="nav-item active">
        <%= link_to 'Home', home_about_path ,class:"nav-link" %>
      </li>

      <li class="nav-item active">
        <%= link_to 'SLA Calc',  slacal_index_path ,class:"nav-link" %>
      </li>

      <li class="nav-item active">
        <%= link_to 'Index', home_index_path ,class:"nav-link" %>
      </li>

      <li class="nav-item active">
        <%= link_to 'Machine type', machinetype_index_path ,class:"nav-link" %>
      </li>

      <li class="nav-item active">
        <%= link_to 'Random Questions', qanas_path ,class:"nav-link" %>
      </li>

      <li class="nav-item active">
        <%= link_to 'Interview Questions',  interview_index_path ,class:"nav-link" %>
     </li>

      <li class="nav-item active">
        <%= link_to 'Grokking', grokkings_path ,class:"nav-link" %>
      </li>
 
      <li class="nav-item active">
        <%= link_to 'CPU Core', getcpu_path ,class:"nav-link" %>
      </li>

  
  
   
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>


  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>Hello second professional webpage for Quiz</p>

<p>---</p>
<%= @name %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Hello first professional webpage for Quiz</p>

<br/>

<%= form_tag home_index_path ,:method => 'POST' do %>

	<%= select_tag(:team_number , options_for_select([
							['1','1'],
							['2','2'],
							['3','3'],
							]),	class: 'form-control') %>
	
	<%= submit_tag 'Create SLA' , class:"btn btn-primary" %>

	 
<% end %>

app/views/interview/index.html.erb
<h1>Interview#index</h1>
<p>Find me in app/views/interview/index.html.erb</p>

app/views/slacal/index.html.erb
<div class="main">
	<div class="container">
		<h1> Welcome to SLA Calculator page - Index </h1>
		<p1> Use the calculator to calculate sequnetial and composite SLA - Index </p1>
 

 		<%= form_tag slacal_index_path ,  :method => 'POST' do %>
			<%= text_field_tag 'System1' , nil ,placeholder: "Enter System 1 SLA" , size:50 %></br>
			<%= text_field_tag 'System2' , nil ,placeholder: "Enter System 2 SLA" , size:50 %></br>
			<%= text_field_tag 'System3' , nil ,placeholder: "Enter System 3 SLA" , size:50 %></br>
			<%= text_field_tag 'System4' , nil ,placeholder: "Enter System 4 SLA" , size:50 %></br>

			<%= submit_tag 'Calculate sequnetial SLA ' %>

			
		<% end %>
		<%= @sla %>

	</div>
</div>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>