config/routes.rb
Rails.application.routes.draw do
  get 'machinetype/index'
  root 'home#about'
  get 'home/about'
  get 'home/index'
  post 'home/index' => 'home#index'
  #get 'welcome/home'
  resources :aboutmes
  resources :grokkings
  resources :qanas
  resources :cpurcores
  resources :slacal

  get 'getcpu' => 'cpucores#home'
  get 'slacal/home_' => 'slacal#home '
  get 'home/about'
  get 'interview/index'
  post "machinetype/index" => 'machinetype#index'
  #post "home/aboutmes" => 'aboutmes#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aboutme.rb
class Aboutme < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grokking.rb
class Grokking < ApplicationRecord
end

app/models/qana.rb
class Qana < ApplicationRecord
end

app/controllers/cpucores_controller.rb
class CpucoresController < ApplicationController
	def home
		require 'net/http'
		
		@symbol = params[:sym]
		@url  =  'https://docs.microsoft.com/en-us/azure/virtual-machines/acu'
	end
end

app/controllers/grokkings_controller.rb
class GrokkingsController < ApplicationController
  before_action :set_grokking, only: [:show, :edit, :update, :destroy]

  # GET /grokkings
  # GET /grokkings.json
  def index
    @grokkings = Grokking.all
  end

  # GET /grokkings/1
  # GET /grokkings/1.json
  def show
  end

  # GET /grokkings/new
  def new
    @grokking = Grokking.new
  end

  # GET /grokkings/1/edit
  def edit
  end

  # POST /grokkings
  # POST /grokkings.json
  def create
    @grokking = Grokking.new(grokking_params)

    respond_to do |format|
      if @grokking.save
        format.html { redirect_to @grokking, notice: 'Grokking was successfully created.' }
        format.json { render :show, status: :created, location: @grokking }
      else
        format.html { render :new }
        format.json { render json: @grokking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grokkings/1
  # PATCH/PUT /grokkings/1.json
  def update
    respond_to do |format|
      if @grokking.update(grokking_params)
        format.html { redirect_to @grokking, notice: 'Grokking was successfully updated.' }
        format.json { render :show, status: :ok, location: @grokking }
      else
        format.html { render :edit }
        format.json { render json: @grokking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grokkings/1
  # DELETE /grokkings/1.json
  def destroy
    @grokking.destroy
    respond_to do |format|
      format.html { redirect_to grokkings_url, notice: 'Grokking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grokking
      @grokking = Grokking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grokking_params
      params.require(:grokking).permit(:topic, :article, :creationdate)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index, :team , :about]

  def common
  	@name ="Krishna Venkat"
  	@team_selected = 0
  end 

  def team

  end 

  def index
  	  	@team_selected = params[:team_number]
  end

 def about 
 end

end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController
  def index
  end
end

app/controllers/qanas_controller.rb
class QanasController < ApplicationController
  before_action :set_qana, only: [:show, :edit, :update, :destroy]

  # GET /qanas
  # GET /qanas.json
  def index
    @qanas = Qana.all
  end

  # GET /qanas/1
  # GET /qanas/1.json
  def show
  end

  # GET /qanas/new
  def new
    @qana = Qana.new
  end

  # GET /qanas/1/edit
  def edit
  end

  # POST /qanas
  # POST /qanas.json
  def create
    @qana = Qana.new(qana_params)

    respond_to do |format|
      if @qana.save
        format.html { redirect_to @qana, notice: 'Qana was successfully created.' }
        format.json { render :show, status: :created, location: @qana }
      else
        format.html { render :new }
        format.json { render json: @qana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qanas/1
  # PATCH/PUT /qanas/1.json
  def update
    respond_to do |format|
      if @qana.update(qana_params)
        format.html { redirect_to @qana, notice: 'Qana was successfully updated.' }
        format.json { render :show, status: :ok, location: @qana }
      else
        format.html { render :edit }
        format.json { render json: @qana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qanas/1
  # DELETE /qanas/1.json
  def destroy
    @qana.destroy
    respond_to do |format|
      format.html { redirect_to qanas_url, notice: 'Qana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qana
      @qana = Qana.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qana_params
      params.require(:qana).permit(:topic, :question, :answer, :createddate, :version)
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
end

app/controllers/slacal_controller.rb
class SlacalController < ApplicationController
 	def index
		@sla  = 10
	end

	def create
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cpucores_helper.rb
module CpucoresHelper
end

app/helpers/grokkings_helper.rb
module GrokkingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interview_articles_helper.rb
module InterviewArticlesHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/machinetype_helper.rb
module MachinetypeHelper
end

app/helpers/qanas_helper.rb
module QanasHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/slacal_helper.rb
module SlacalHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grokkings/_form.html.erb
<%= form_with(model: grokking, local: true) do |form| %>
  <% if grokking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grokking.errors.count, "error") %> prohibited this grokking from being saved:</h2>

      <ul>
        <% grokking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_area :article %>
  </div>

  <div class="field">
    <%= form.label :creationdate %>
    <%= form.datetime_select :creationdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grokkings/edit.html.erb
<h1>Editing Grokking</h1>

<%= render 'form', grokking: @grokking %>

<%= link_to 'Show', @grokking %> |
<%= link_to 'Back', grokkings_path %>

app/views/grokkings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grokkings</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Article</th>
      <th>Creationdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grokkings.each do |grokking| %>
      <tr>
        <td><%= grokking.topic %></td>
        <td><%= grokking.article %></td>
        <td><%= grokking.creationdate %></td>
        <td><%= link_to 'Show', grokking %></td>
        <td><%= link_to 'Edit', edit_grokking_path(grokking) %></td>
        <td><%= link_to 'Destroy', grokking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grokking', new_grokking_path %>

app/views/grokkings/new.html.erb
<h1>New Grokking</h1>

<%= render 'form', grokking: @grokking %>

<%= link_to 'Back', grokkings_path %>

app/views/grokkings/show.html.erb
<p id="notice"><%= notice %></p>

<h>Show question</h>
<p>
  <strong>Topic:</strong>
  <%= @grokking.topic %>
</p>

<p>
  <strong>Article:</strong>
  <%= @grokking.article %>
</p>

<p>
  <strong>Creationdate:</strong>
  <%= @grokking.creationdate %>
</p>

<%= link_to 'Edit', edit_grokking_path(@grokking) %> |
<%= link_to 'Back', grokkings_path %>

app/views/qanas/_form.html.erb
<%= form_with(model: qana, local: true) do |form| %>
  <% if qana.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qana.errors.count, "error") %> prohibited this qana from being saved:</h2>

      <ul>
        <% qana.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="field">
    <%= form.label :createddate %>
    <%= form.datetime_select :createddate %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
 
<% end %>

app/views/qanas/edit.html.erb
<h1>Editing Question and Answer</h1>

<%= render 'form', qana: @qana %>

<%= link_to 'Show', @qana %> |
<%= link_to 'Back', qanas_path %>

app/views/qanas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>New Azure Quesitons and Answers</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Createddate</th>
      <th>Version1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qanas.each do |qana| %>
      <tr>
        
        <td><%= qana.topic %></td>
        <td><%= qana.question %></td>
        <td><%= qana.answer %></td>
        <td><%= qana.createddate %></td>
        <td><%= qana.version %></td>



        <td><%= link_to 'Show', qana %></td>
        <td><%= link_to 'Edit', edit_qana_path(qana) %></td>
        <td><%= link_to 'Destroy', qana, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qana', new_qana_path %>

app/views/qanas/new.html.erb
<h1>Answer the Quiz</h1>

<%= render 'form', qana: @qana %>

<%= link_to 'Back', qanas_path %>

app/views/qanas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @qana.topic %>
</p>

<p>
  <strong>Question:</strong>
  <%= @qana.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @qana.answer %>
</p>

<p>
  <strong>Createddate:</strong>
  <%= @qana.createddate %>
</p>

<p>
  <strong>Version:</strong>
  <%= @qana.version %>
</p>
 

<%= link_to 'Edit', edit_qana_path(@qana) %> |
<%= link_to 'Back', qanas_path %>